### ISSUE TITLE
Enhance french translation

### ISSUE THREAD

**Issue by LaurentGrenet** [IgorMagellan/Tiramisu#1]
First of all, thank you to have added french translation !

But about it, "Contour line" should be said in french "Courbes de niveau" (rather than "Lignes de contour" that is not meaningful in french)
Be aware : Two occurences to modify in Tiramisu.xml : layer id="tms_contours" and layer id="tms_contours-lz"

Another slight modification : about layer id="tms_culture", french translation to "Trucs culturels" is OK, but not very "correct". "Eléments culturels" would be a lot better !

**Comment by IgorMagellan** [comment]
Thanks for the hints. Translation was done by google translator. Changes made to the main repository.
